pipeline:
  build:
    image: rails-qna
    commands: 
      - cp config/database.yml.drone config/database.yml
      - bundle exec rake db:drop
      - bundle exec rake db:create
      - bundle exec rake db:migrate
      - bundle exec rspec --color
    when:
      branch: master
services:
  db:
    image: postgres