os: osx
language: ruby
rvm:
  - "2.3.0"
services:
  - postgresql
script: bundle exec rspec
before_install:
  - brew update
  - brew install mysql
  - brew instal sphinx --pgsql --mysql
  - brew install qt5
  - brew install redis
before_script:
  - bundle exec rackup private_pub.ru -s thin -E production &
  - cp config/database.yml.travis config/database.yml
  - cp config/private_pub.yml.sample config/private_pub.yml
  - psql -c 'create database travis_ci_test;' -U postgres
