osx_image: xcode7.3
language: objective-c
cache: bundler
rvm:
  - 2.3.0

script: bundle exec rspec
before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.0
  - sudo gem install bundler
  - brew update
  - brew install mysql
  - brew instal sphinx --with-pgsql --with-mysql
  - brew install qt5
  - brew linkapps qt5
  - brew link --force qt5
  - brew install redis
before_script:
  - bundle exec rackup private_pub.ru -s thin -E production &
  - cp config/database.yml.travis config/database.yml
  - cp config/private_pub.yml.sample config/private_pub.yml
  - psql -c 'create database travis_ci_test;' -U postgres
